import './globals.css'
import type { Metadata } from 'next'
import { roboto } from '../assets/fonts'


export const metadata: Metadata = {
  title: 'Weather App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  )
}
